import { Toaster } from "react-hot-toast";
import AuthProvider from "../providers/authProvider";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <AuthProvider>

          {children}

        </AuthProvider>

        <Toaster toastOptions={{ duration: 1000 }} />

      </body>
    </html>
  );
}
