import axios from 'axios';
import { getServerSession } from 'next-auth';
import Link from 'next/link';
import React from 'react'
import { options } from './api/auth/[...nextauth]/options';


export const metadata = {
  title: "Jio Jee",
  description: "Generated by create next app",
};


export default async function Page() {

  // const { user } = await getServerSession(options);
  // console.log(user);

  // const response = await axios.get('http://localhost:3000/api/products');

  // console.log(response.data);
  return (
    <div>

      <Link href={'/dashboard'}>Dashboard</Link>



    </div>
  )
}
