import axios from 'axios';
import React from 'react'

export const metadata = {
  title: "Jio Jee",
  description: "Generated by create next app",
};


export default async function Page() {

  const response = await axios.get('http://localhost:3000/api/products');

  console.log(response.data);
  return (
    <div>

      <h1>hello jee</h1>

    </div>
  )
}
